---
- name: 팩트 파일 생성
  hosts: web1
  vars:
    remote_dir: /etc/ansible/facts.d
    facts_file: custom.fact
  tasks:
    # 1) /etc/ansible/facts.d/ 디렉토리 생성
    # 2) custom.fact 파일 배포

    # 1) /etc/ansible/facts.d/ 디렉토리 생성
    - name: 안녕 {{ remote_dir }} 디렉토리 생성
      file:
        path: "{{ remote_dir }}"
        state: directory
    # 2) custom.fact 파일 배포
    - name: 안녕 {{ custom.fact }} 파일 배포
      copy:
        src: "{{ facts_file }}"
        dest: "{{ remote_dir }}"