---
- name: Restore factcheck.yml
  hosts: all
  tasks:
    # (주의) web1, web2, web3, web4
    # 1) 웹 서비스 종료 - httpd, firewalld
    # 2) 웹 서비스 설정 파일 삭제 - /var/www/html/index.html
    # 3) 웹 패키지 삭제 - httpd, mod_ssl, firewalld
    - name: 웹 서비스 종료
      service:
        name: "{{ item }}"
        state: stopped
        enabled: no
      loop:
        - httpd
        - firewalld
    - name: 웹 서비스 설정 파일 삭제
      file:
        path: /var/www/html/index.html
        state: absent
    - name: 웹 패키지 삭제
      yum:
        name:
          - httpd
          - mod_ssl
          - firewalld
        state: absent